Repository puppetlabs/puppetlabs-vcsrepo, pull requests merged in 2019-11, with the labels that each got.

#432 feat: do not chown excluded files
  lib/puppet/provider/vcsrepo.rb
  spec/unit/puppet/provider/vcsrepo/git_spec.rb
Labels: bugfix

#434 pdksync - FM-8499 remove ubuntu 14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#433 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .rubocop.yml
  .sync.yml
  .travis.yml
  .yardopts
  Gemfile
  README.md
  Rakefile
  metadata.json
  spec/default_facts.yml
Labels: maintenance
