Repository puppetlabs/puppetlabs-vcsrepo, pull requests merged in 2019-04, with the labels that each got.

#409 Use clearer error message for "This client is too old to work with the working copy"
  lib/puppet/provider/vcsrepo/svn.rb
Labels: maintenance

#414 MODULES-8910 fix for failing git install using RepoForge instead of epel
  spec/spec_helper_acceptance.rb
Labels: bugfix

#413 pdksync - (MODULES-8444) - Raise lower Puppet bound
  metadata.json
Labels: backwards-incompatible

#415 pdksync - (maint) Update pdk-template to f778803
  .gitignore
  .pdkignore
  .puppet-lint.rc
  .travis.yml
  metadata.json
Labels: maintenance

#416 (MODULES-8738) Allow Sensitive value for basic_auth_password
  README.markdown
  lib/puppet/provider/vcsrepo/hg.rb
  lib/puppet/provider/vcsrepo/svn.rb
  lib/puppet/type/vcsrepo.rb
  spec/unit/puppet/provider/vcsrepo/hg_spec.rb
  spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Labels: feature
