Repository puppetlabs/puppetlabs-vcsrepo, pull requests merged in 2021-02, with the labels that each got.

#489 pdksync - Update gha templates
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .rubocop.yml
  .travis.yml
  Rakefile
  lib/puppet/type/vcsrepo.rb
  metadata.json
Labels: maintenance

#490 (MODULES-9997) - Removing extra unwrap on Sensitive value
  lib/puppet/provider/vcsrepo/svn.rb
  spec/acceptance/svn_spec.rb
  spec/unit/puppet/provider/vcsrepo/svn_spec.rb
Labels: bugfix

#493 (IAC-1440) Release Prep PR version 3.2.1
  CHANGELOG.md
  metadata.json
Labels: maintenance

#491 pdksync - Remove Puppet 5 from testing and bump minimal version to 6.0.0
  .github/workflows/auto_release.yml
  .rubocop.yml
  .sync.yml
  .travis.yml
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#500 pdksync - (MAINT) Remove RHEL 5 family support
  metadata.json
Labels: maintenance

#501 pdksync - (MAINT) Remove SLES 11 support
  metadata.json
Labels: maintenance
