Repository puppetlabs/puppetlabs-vcsrepo, pull requests merged in 2022-10, with the labels that each got.

#570 pdksync - (CONT-130) - Dropping Support for Debian 9
  metadata.json
Labels: bugfix, hacktoberfest

#572 pdksync - (PDKSync) Removal of puppet_module_gems
  .devcontainer/README.md
  Gemfile
  metadata.json
Labels: maintenance, hacktoberfest

#573 pdksync - (CONT-189) Remove support for RedHat6 / OracleLinux6 / Scientific6
  metadata.json
Labels: bugfix, hacktoberfest

#574 support umask for git repos (try 2)
  README.md
  lib/puppet/provider/vcsrepo.rb
  lib/puppet/provider/vcsrepo/git.rb
  lib/puppet/type/vcsrepo.rb
  spec/acceptance/clone_repo_spec.rb
Labels: community

#575 fix repeated acceptance tests on the same container
  spec/acceptance/clone_repo_spec.rb
Labels: community
