Repository puppetlabs/puppetlabs-vcsrepo, pull requests merged in 2022-06, with the labels that each got.

#548 (GH-540) Fix acceptance test failures
  spec/acceptance/clone_repo_spec.rb
  spec/acceptance/create_repo_spec.rb
  spec/acceptance/multiple_remotes_spec.rb
  spec/acceptance/remove_repo_spec.rb
  spec/acceptance/revision_spec.rb
  spec/spec_helper_acceptance_local.rb
Labels: maintenance

#546 document vcsrepo with git and http proxy
  README.md
Labels: community

#553 (GH-552) Fix home directory evaluation
  lib/puppet/provider/vcsrepo/git.rb
Labels: bugfix

#543 pdksync - (GH-cat-12) Add Support for Redhat 9
  metadata.json
Labels: feature
